
cluster:
  name: "docker-cluster"
network:
  host: "0.0.0.0"
http:
  host: 0.0.0.0

xpack.license.self_generated.type: ${LICENSE}

xpack.security.enabled: true

# transport security settings
# This is mostly used for inter-node communications between parts of the ELK stack
xpack:
  security:
    transport:
      ssl:
        enabled: true
        key: ${CONFIG_DIR}/elasticsearch.key
        certificate: ${CONFIG_DIR}/elasticsearch.crt
        certificate_authorities: ${CONFIG_DIR}/ca.crt
# HTTP security setttings
# This is used for client server ssl/tls communications (e.g. browser to kibana)
    http:
      ssl:
        enabled: true
        key: ${CONFIG_DIR}/elasticsearch.key
        certificate: ${CONFIG_DIR}/elasticsearch.crt
        certificate_authorities: ${CONFIG_DIR}/ca.crt