name: filebeat

filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - "../../../../Project/AppTest/hello/logs/application.log"

output.logstash:
    enabled: true
    hosts: ["logstash:5044"]
    ssl.certificate_authorities: ["${CONFIG_DIR}/ca.crt"]
    ssl.certificate: "${CONFIG_DIR}/filebeat.crt"
    ssl.key: "${CONFIG_DIR}/filebeat.key"