- pipeline.id: normal-beats
  path.config: "/usr/share/logstash/pipeline/beat.conf"
  pipeline.workers: 3

- pipeline.id: http
  path.config: "/usr/share/logstash/pipeline/http.conf"
  pipeline.workers: 3

- pipeline.id: jdbc
  path.config: "/usr/share/logstash/pipeline/jdbc.conf"
  pipeline.workers: 3
