- pipeline.id: normal-beats
  path.config: "${LOGSTASH_DIR}/pipeline/beat.conf"
  pipeline.workers: 3

- pipeline.id: http
  path.config: "${LOGSTASH_DIR}/pipeline/http.conf"
  pipeline.workers: 3

- pipeline.id: jdbc
  path.config: "${LOGSTASH_DIR}/pipeline/jdbc.conf"
  pipeline.workers: 3
